name: Generate routing rules for Surge
on:
  workflow_dispatch:
  schedule:
    - cron: "50 23 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the default branch
      uses: actions/checkout@v4

    - name: Download proxy.txt
      run: |
        curl -sSL https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/proxy.txt > proxy.txt

    - name: Remove breaked urls
      run: |
        grep -v 'enterprise.ac.uk' proxy.txt > proxy_cleaned.txt

    - name: Commit
      run: |
        TODAY=$(date +"%Y-%m-%d")
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add proxy_cleaned.txt
        git commit -m "$TODAY"
        git push

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: proxy_cleaned.txt
        name: "Release ${{ steps.date.outputs.date }}"
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
