name: Generate routing rules for Surge
on:
  workflow_dispatch:
  schedule:
    - cron: "50 23 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the default branch
      uses: actions/checkout@v4

    - name: Download proxy.txt
      run: |
        curl -sSL https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/proxy.txt > proxy.txt

    - name: Remove breaked urls
      run: |
        grep -v 'enterprise.ac.uk' proxy.txt > proxy_cleaned.txt

    - name: Set release tag and name
      run: |
        TAG_NAME="v$(date +'%Y%m%d')"
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
        echo "RELEASE_NAME=${TAG_NAME} Release" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ env.RELEASE_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        draft: false
        prerelease: false
        files: proxy_cleaned.txt
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
